<?php

/**
 * @file
 * Contains modiblog.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function modiblog_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the modiblog module.
    case 'help.page.modiblog':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function modiblog_theme() {
  return [
    'modiblog' => [
      'render element' => 'children',
    ],
  ];
}

function modiblog_preprocess_page(&$variables) {
  if (\Drupal::theme()->getActiveTheme()->getName() == 'seven' ) {
    $variables['#attached']['library'][] = 'modiblog/ckeditor-codesnippet-rtl';
  }
}
